### ISSUE TITLE
Request : Ketoprak 

### ISSUE THREAD

**Issue by ghost** [rasyidev/restoran#1]
Resep liat ini aja -> https://cookpad.com/id/resep/15681454-ketoprak-jakarta

**Comment by rasyidev** [comment]
> Resep liat ini aja -> https://cookpad.com/id/resep/15681454-ketoprak-jakarta

Nice, silahkan tambahkan aja. Nanti boleh Pull Request

**Comment by ghost** [comment]
Okeh

Pada tanggal Sen, 15 Nov 2021 16.01, Habib Abdurrasyid <
***@***.***> menulis:
